services:
  nuxt:
    container_name: portfolio_new
    build: .
    volumes:
      - .:/website_front
    ports:
      - "80:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - CHOKIDAR_USEPOLLING=true
#    command: sh -c "yarn && yarn dev"